### ISSUE TITLE
Player resources

### ISSUE THREAD

**Issue by jonastikov** [Jalict/OOSE-LunarLander#11]
Array with the different resource types

**Comment by Jalict** [comment]
I think the basic resource should just be a simple int/float. Which will increase whenever the player starts mining and decrease whenever they sell it or maybe if they can convert into something else (Fuel, booster, health)

**Comment by jonastikov** [comment]
Make so that when you get near a planet and is landed properly. Then you have the ability to mine the planet from resources,

**Comment by jonastikov** [comment]
Add variable to player to hold resources
Add getter and setter functions
