### ISSUE TITLE
Damage Model

### ISSUE THREAD

**Issue by Jalict** [Jalict/OOSE-LunarLander#15]
The player's ship should be able to be damaged in various way:
* Collision with objects
  * Planets
  * Asteroids
* Overheat from Suns
* Aliens/Natives of the planets

The way that the damage might work could ex. be; Whenever the ship falls into the planet, we get the speed and multiple that into a constant and damage by that amount (velocity * Damage constant = amount of damage). 
But it could also be much simpler that whenever they hit something at whatever speed, they just lose 10% health.

Depends on the scope and concept of what we just want in the end :+1:

**Comment by Prawnkus** [comment]
Ship now damaged when collision is true and speed > 0,1.
TODO: Damage only once, when ship hits surface instead of looping the damage onto the ship.

**Comment by Prawnkus** [comment]
Damage model is now multiplication of player velocity, if player collides with planet at threshold speed or higher.
