### ISSUE TITLE
Make Objects to inherit Slick2D's Shapes 

### ISSUE THREAD

**Issue by Jalict** [Jalict/OOSE-LunarLander#17]
Current both of our Planet & Player is considered to be some very primitive shapes. A rectangle and a circle. Those have some very basic characteristics such as position and size. Current we have made our own variables. 

BUT Slick2D already have a class called Shapes where several primitives inherits from (See http://slick.ninjacave.com/javadoc/org/newdawn/slick/geom/Shape.html).

This could come to GREAT use as we would have some basic functions already implemented for us, but also more advanced once such as intersections!
The graphics class even understands what a shape is and can fully draw them easily.

**Comment by jonastikov** [comment]
Collision correction
