### ISSUE TITLE
Basic Movement

### ISSUE THREAD

**Issue by Jalict** [Jalict/OOSE-LunarLander#2]
Make basic movement so that the player can move around the screen (Left, Right, Up & Down)

**Comment by jonastikov** [comment]
Lunar lander only moves in three directions

**Comment by Jalict** [comment]
Will properly have 3 local variables
Vector2f = position, rotation, thrustdir

Position is the current position of the ship.
Rotation is the current rotation of the ship (Ship can rotate in other direction in which it is actually flying).
Acceleration is the current moving direction. Will be affected by forces such as Thrusting, gravity, collision.

This is the basics of the movement

**Comment by Jalict** [comment]
I changed a bit form the previous scheme. Acceleration still exist, but is now named velocity (Thanks Unity3D!)
And now we have a float rotation and thrust.
Those two values is applied to the velocity each update. And the thrust and rotation is directed by the users input.
If they press A/D the ships gets rotated either left or right.
And if they press W/S the ship either gets more velocity or starts braking.
This gives us the degree of freedom that the ship can rotate while moving in another direction - But you can thrust in the opposite vector of the velocity to stop it and etc. 
Works fantastic!
