### ISSUE TITLE
Basic planet collision 

### ISSUE THREAD

**Issue by jonastikov** [Jalict/OOSE-LunarLander#3]
Detect collision with planet. If over speed something the plane gets damaged. Should output with which planet collision is detected.

**Comment by jonastikov** [comment]
So I've implemented a not fully working code for collision, but cannot push it due to conflict issues. Here is the code anyways	
// in render
	
g.drawString("Collision: " + collision(), 10, 120);


// class method / function

		//TODO Output which planet player is intersecting (perhaps change to void)
	public boolean collision(){							// Detect player/planet intersection
		boolean col = false;
	for(int i = 0;i < planet.size();i++) {				// check all planets
		if (player.intersects(planet.get(i)) == true){
			col = true;									// change output to true if player intersects any planet
			}
		}
	return col;
	}

**Comment by Jalict** [comment]
We'll look into this sometime next week!

**Comment by Jalict** [comment]
I have actually looked a bit further into the problem. Collision in itself isn't hard - It is the response that is hard!
If we choose the player to be a circle for now, then it would be much easier.
