### ISSUE TITLE
Fix crash when trying to mine from HomePlanet

### ISSUE THREAD

**Issue by Jalict** [Jalict/OOSE-LunarLander#40]
Whenever you get near a HomePlanet and try do Mine (Using the key 'm'). Then the game crashes with the exception:
```Java
java.lang.ClassCastException: LanderGame.Homeplanet cannot be cast to LanderGame.ResourcePlanet
	at LanderGame.Game.update(Game.java:77)
```
This might have something to do that we check is we check for EVERY planet that we do the mining. We should properly only do the key check (at line 76, game.java) for the planet ResourcePlanet.

**Comment by jonastikov** [comment]
I would also suggest that we place Homeplanet at planets(0) for convenience. Then it would be easy to skip in the the for loop as well.

**Comment by Jalict** [comment]
Seems like a quick solution! :+1:

**Comment by jonastikov** [comment]
However now I fixed it properly. It was just a quick-fix I forgot to replace....
