### ISSUE TITLE
World Space Boundries

### ISSUE THREAD

**Issue by Jalict** [Jalict/OOSE-LunarLander#53]
When the player floats to a certain space away from the homeplanet, then a warning will start appearing that they are about to leave the "level". (Will be warned as Radiations)

They will slowly loose health and the screen will get read.

This also be useful to set some boundaries for #10.

**Comment by Prawnkus** [comment]
Boundries set with warning. Needs damage model and visual feedback (sound of geiger counter?)

**Comment by Prawnkus** [comment]
Visual feedback and sound now implemented.

**Comment by Prawnkus** [comment]
Needs visual representation of borders
