### ISSUE TITLE
Player information

### ISSUE THREAD

**Issue by Jalict** [Jalict/OOSE-LunarLander#9]
Give the user information about the speed, fuel, upgrades, health, etc. of the ship, in form of graphical user interface.

**Comment by Jalict** [comment]
There is several parameters and information that should be giving the player. Those are some of the examples I've come up with that I at least KNOW that can be added for the current concept of the game:
* Player speed ("Velocity" - Could also be separated with horizontal & vertical velocity)
* Amount of resources and total space for them
* Current thrust speed and the maximum achievable speed
* A mini-map which indicates where the player is and the planets

**Comment by jonastikov** [comment]
We make one long menu consisting of two sections; ship, upgrade.
In ship user can choose from: refuel and repair
In Upgrade user can see which upgrade he/she can afford highlighted from a list of all available upgrades.

**Comment by Prawnkus** [comment]
Ship UI implemented in lower left, with thrust, speed, armour and fuel bars.
Speed number needs work.
